### ISSUE TITLE
How do you take notes?

### ISSUE THREAD

**Issue by dufferzafar** [keyvanakbary/learning-notes#3]
Hey, your notes are pretty good! I wonder how you actually take them? as in do you read physical books or ebooks? Do you type out the notes while reading or make a second pass over the book?

I too have tried taking notes but I feel it slows me down considerably and then I just can't move ahead with the book.

**Comment by keyvanakbary** [comment]
Hey Shadab, sorry for the delay.

Thanks a lot for your kind words! :)

I do always try to read digital material (epub mainly) so I can highlight it safely. For books I find the combination of an iPad mini (lightweight, good for tech books) + iBooks app (great UI, synced will all devices) really good for notes. As you said, writing notes down while reading may significantly slow you down.

I do usually highlight what I do consider important with the iBooks app while reading, and then transcribe it right down to a markdown file right after I read a chapter (as a recall exercise). After I read the entire book I do a few tweaks and then publish. The idea is to refine the summary after a few reading iterations, keeping it shorter each time.

I will be super honest tho, taking notes afterwards (recalling the material you've just read) is insanely tedious, but it definitively pays off. You will not only retain learning longer in time, but you'll have something to come back (I do keep coming back to the files I created continuously).

Thanks!
